"""Gate the pilot/data-cell tables against the constant-data-carrier identity.

``atsc3lib.data.pilot_tables.json`` is generated by
``tools/fetch_pilot_tables.py`` from the pinned independent transcription.  The
identity (A/322 8.1.4.1) is rebuilt here from the banked tables so a stale or
corrupt JSON is caught without the network: for every FFT size, cred_coeff and
allowed pattern, the pilot grid must yield exactly the tabulated data count.
"""

import pytest

from atsc3lib import pilot_tables, spec

FFT_SIZES = (8192, 16384, 32768)
CRED_VALUES = (0, 1, 2, 3, 4)


def _data_count(fft, cred, pattern):
    noc = pilot_tables.noc(fft, cred)
    cp = set(pilot_tables.common_cp_relative(fft, cred))
    add = set(pilot_tables.additional_cp(fft, pattern, cred))
    dx, dy = spec.SP_DXDY[pattern]
    counts = set()
    for phase in range(dy):
        pilots = set(range(dx * phase, noc, dx * dy)) | {0, noc - 1} | cp | add
        counts.add(noc - len(pilots))
    return counts


@pytest.mark.parametrize('fft', FFT_SIZES)
def test_identity_matches_allowed_patterns(fft):
    allowed = spec.allowed_patterns(fft)
    for cred in CRED_VALUES:
        for pattern in spec.SP_DXDY:
            counts = _data_count(fft, cred, pattern)
            expect = pilot_tables.avail_data(fft, cred, pattern)
            if pattern in allowed:
                assert counts == {expect}, (
                    f'{fft}/{cred}/{pattern}: {counts} != {expect}')
            else:
                # Not-allowed patterns are not constant-phase (Table 8.3).
                assert len(counts) > 1 or expect == 0


def test_sbs_total_minus_active_is_null():
    # Annex F active never exceeds Tables 7.5/7.6 total; their difference is
    # the null-cell count (A/322 7.2.6.4).
    for fft in FFT_SIZES:
        for cred in CRED_VALUES:
            for pattern in spec.SP_DXDY:
                total = pilot_tables.sbs_total(fft, cred, pattern)
                active = pilot_tables.sbs_active(fft, cred, 0, pattern)
                if total == 0:
                    continue
                assert active <= total
