"""A/322 7.1.5.2 HTI Cell Interleaver.

The HTI time interleaver of a data PLP with ``L1D_plp_TI_mode == 2`` starts
with a cell interleaver that permutes the cells *within* each FEC block.  It
is optional, signalled by ``L1D_plp_HTI_cell_interleaver``; RF33 sends 0, so
this stage is bypassed there, but a multiplex that sends 1 (e.g. field-site
RF8) hands the LDPC a permuted codeword that cannot converge at any SNR.

Per FEC block index ``r`` (reset at each TI block) the output is::

    d_i,q = g_i,L_r(q)
    L_r(q) = [L_0(q) + P(r)] mod N_cells

``L_0`` is the basic permutation generated by an ``N_d``-bit LFSR word
``R_i`` whose values ``>= N_cells`` are discarded, with ``N_d = ceil(log2
N_cells)`` and LFSR feedback taps per ``N_d`` (A/322 7.1.5.2)::

    R_i[N_d-1]                 = i mod 2
    R_i[N_d-2, N_d-3, ..., 1]  = R_{i-1}[N_d-3, ..., 0]     (2 < i < 2^N_d)
    R_i[N_d-2]                 = XOR of R_{i-1} taps[1:]

``P(r)`` is the bit-reversal of a counter ``k`` over ``N_d`` bits, skipping
bit-reversed values ``>= N_cells``.

The generator is gated on the test vector A/322 7.1.5.2 prints in its own
text (``N_cells = 10800``, ``N_d = 14`` -> ``0, 8192, 4096, 2048, 10240,
6144, 1024, 9216``).

Receiver side: the transmitter emits ``out[j] = in[C_r(j)]`` (with ``C_r``
the permutation above), so the receiver scatters ``in[C_r(j)] = out[j]``.

Reference: ATSC A/322:2024-04, Section 7.1.5.2.
"""

from dataclasses import dataclass
from typing import Dict

import numpy as np

#: LFSR feedback taps (indices into ``R_{i-1}``) per ``N_d``, A/322 7.1.5.2.
TAPS: Dict[int, tuple] = {
    11: (0, 3),
    12: (0, 2),
    13: (0, 1, 4, 6),
    14: (0, 1, 4, 5, 9, 11),
    15: (0, 1, 2, 12),
}


@dataclass(frozen=True)
class SpecVector:
    """A test vector A/322 7.1.5.2 prints in its own text."""
    ncells: int
    expect: tuple


#: A/322 7.1.5.2 printed shift vector, N_cells=10800 (N_d=14), r=0..7.
GOLD = SpecVector(ncells=10800,
                  expect=(0, 8192, 4096, 2048, 10240, 6144, 1024, 9216))


class CellInterleaver:
    """A/322 7.1.5.2 cell interleaver for one FEC-block length ``ncells``.

    ``ncells`` is the FEC block cell count ``N_inner / eta_MOD`` (A/322
    Table 6.14), e.g. 2700 for 64QAM at ``N_inner = 16200``.
    """

    def __init__(self, ncells: int):
        self.ncells = int(ncells)
        self.nd = self._nd_for(self.ncells)
        self.l0 = self._basic_permutation(self.ncells)

    @staticmethod
    def _nd_for(ncells: int) -> int:
        """``N_d = ceil(log2 N_cells)``, restricted to the tapped widths."""
        nd = int(np.ceil(np.log2(ncells)))
        if nd not in TAPS:
            raise ValueError(
                f"no A/322 7.1.5.2 taps for N_d={nd} (N_cells={ncells})")
        return nd

    def _basic_permutation(self, ncells: int) -> np.ndarray:
        """``L_0(q)``: the basic permutation, length ``ncells``."""
        taps = TAPS[self.nd]
        out = np.empty(ncells, np.int64)
        q = 0
        prev = np.zeros(self.nd, np.uint8)
        weights = 1 << np.arange(self.nd, dtype=np.int64)
        for i in range(1 << self.nd):
            r = np.zeros(self.nd, np.uint8)
            if i == 2:
                r[0] = 1
            elif i > 2:
                r[0:self.nd - 2] = prev[1:self.nd - 1]
                b = 0
                for t in taps:
                    b ^= int(prev[t])
                r[self.nd - 2] = b
            r[self.nd - 1] = i & 1
            v = int(np.dot(r.astype(np.int64), weights))
            if v < ncells:
                out[q] = v
                q += 1
            prev = r
        if q != ncells:
            raise ValueError(f"L_0 produced {q} values for N_cells={ncells}")
        return out

    def shifts(self, nblocks: int) -> np.ndarray:
        """``P(r)`` for ``r = 0 .. nblocks-1`` (bit-reversed counter, skip large)."""
        out, k = [], 0
        while len(out) < nblocks:
            v = int(format(k, "0%db" % self.nd)[::-1], 2)
            if v < self.ncells:
                out.append(v)
            k += 1
        return np.array(out, np.int64)

    def deinterleave(self, blocks: np.ndarray) -> np.ndarray:
        """Undo 7.1.5.2 for a ``(nblocks, ncells)`` array of one TI block.

        The transmitter reads ``out[j] = in[C_r(j)]`` with ``C_r = (L_0 +
        P(r)) mod ncells``, so the receiver scatters ``in[C_r(j)] = out[j]``.
        """
        blocks = np.asarray(blocks)
        nblk, ncells = blocks.shape
        if ncells != self.ncells:
            raise ValueError(f"expected {self.ncells} cells, got {ncells}")
        pr = self.shifts(nblk)
        out = np.empty_like(blocks)
        for r in range(nblk):
            out[r, (self.l0 + pr[r]) % ncells] = blocks[r]
        return out

    def interleave(self, blocks: np.ndarray) -> np.ndarray:
        """Transmitter side: ``out[r, j] = in[r, C_r(j)]``."""
        blocks = np.asarray(blocks)
        nblk, ncells = blocks.shape
        if ncells != self.ncells:
            raise ValueError(f"expected {self.ncells} cells, got {ncells}")
        pr = self.shifts(nblk)
        return np.stack([blocks[r][(self.l0 + pr[r]) % ncells]
                         for r in range(nblk)])


def gold_vector() -> tuple:
    """Reproduce A/322 7.1.5.2's printed ``P(r)`` example."""
    ci = CellInterleaver(GOLD.ncells)
    return list(ci.shifts(len(GOLD.expect))), list(GOLD.expect)
